---
title: "New Final Project Proposal"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Group members
* Juan Cambeiro (jc5313)
* Jiaxin Wu (jw4007) 
* Liping Lu (ll3407)
* Thirsten Stockton (tjs2193)
* Kiran Kui (yk2959)

## Tentative project title
"HIV/AIDS Trends 1990-2019"

## Motivation
Human immunodeficiency virus (HIV), which is a virus that causes acquired immunodeficiency syndrome (AIDS), is one of the world’s most pressing public health challenges. Since the time it was identified, tens of millions of deaths due to HIV/AIDS have occurred. HIV/AIDS is considered an ongoing pandemic since it is actively spreading globally, and it continues to wreak devastating impacts across the world, and in particular in low-and-middle income countries that have limited resources to address it. It is therefore important and timely to study trends in HIV/AIDS in countries across the world as well as stratified by sociodemographic variables to determine communities and subgroups who are most impacted by the disease. Furthermore, it is important to determine the predictors of HIV/AIDS deaths to develop targeted policies and legislation that can prevent or slow the spread of HIV/AIDS.

## Intended final products
In order to fully assess the impact of HIV/AIDS, several final products will be created. First, we will create an interactive map showing the geographic distribution of HIV/AIDS deaths per 100k by country between 1990 and 2019. Next, we will create time trends assessing the overall global trend of HIV/AIDS deaths per 100k over time and as stratified by sociodemographic variables, as well as the HIV/AIDS death rate by country GDP per capita. Finally, we will do a regression analysis assessing important factors associated with HIV/AIDS.  

## Anticipated data sources
We plan to combine a complex set of open datasets from the following websites:

* HIV/AIDS deaths data by country 1990-2019, by sex and by age group, from the [2019 Global Burden of Disease Study](https://vizhub.healthdata.org/gbd-results/?params=gbd-api-2019-public/c896c16b3ce69e85653c71c75e780f64). 

* GDP per capita by country 1990-2019 from [World Bank data](https://data.worldbank.org/indicator/NY.GDP.PCAP.CD?end=2019&start=1990) 

* Population totals by country 1990-2019, which will allow for adjustment by population size (per 100k) from [World Bank data](https://data.worldbank.org/indicator/SP.POP.TOTL) 


## Planned analyses/visualizations/coding challenges
Planned analyses: 

* Regression model investigating the association between HIV/AIDS deaths per 100k and year, sex, age, interaction of age and sex, and GDP per capita.

Visualizations:

* Global trend of HIV deaths over time
* Global trend of HIV deaths by GENDER over time 
* Global trend of HIV deaths by AGE over time 
* HIV deaths by country GDP
* Countries with the most HIV deaths across the years (interactive graph)

Coding challenges:

* Constructing an interactive map owing the geographic distribution of HIV/AIDS deaths per 100k by country between 1990 and 2019

## Timeline
* 11/15-11/18: Project Review Meeting
* 11/28-11/30: Merge and do exploratory analysis of HIV/AIDS, GDP per capita, and population size datasets.
* 12/1-12/5: Analysis/visualization
* 12/6-12/9: Construct report and generate webpage/screencast
* 12/10: Finishing touches, report due
* 12/15: "In class" discussion of projects