<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analysis</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="timeline.html">HIV/AIDS Timeline</a>
</li>
<li>
  <a href="data.html">Data cleaning/processing</a>
</li>
<li>
  <a href="trends.html">Trends</a>
</li>
<li>
  <a href="dashboard.html">Dashboard</a>
</li>
<li>
  <a href="regression.html">Analysis</a>
</li>
<li>
  <a href="report.html">Final Project Report</a>
</li>
<li>
  <a href="https://www.youtube.com/watch?v=Bg8tbmppoIA">
    <span class="fa fa-brands fa-youtube"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/juancambeiro1/hiv_trends.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Analysis</h1>

</div>


<div id="data" class="section level3">
<h3>Data</h3>
<p><strong>maindata</strong> has 60000 observations and 11 features. We
are adjusting for population size by dividing <code>val</code> (point
estimate of number of HIV/AIDS deaths) by <code>population</code>
multiplied by 100,000 to get a <code>mortality_per_100k</code> variable
and a <code>log_mortality_per_100k</code> variable.</p>
<pre class="r"><code>regression = maindata %&gt;% 
  mutate(mortality_per_100k = val / (population/100000),
         log_mortality_per_100k = log(mortality_per_100k),
         year_2004 = if_else(year &lt;= 2004, 1, 0),
         year_2004 = as.factor(year_2004),
         country_name = as.factor(country_name)) 
regression %&gt;% 
  summarize(col_name = colnames(regression),
            n_missing = map(regression, ~sum(is.na(.)))) %&gt;% 
  unnest(n_missing)</code></pre>
<pre><code>## # A tibble: 14 × 2
##    col_name               n_missing
##    &lt;chr&gt;                      &lt;int&gt;
##  1 location_id                    0
##  2 country_name                   0
##  3 year                           0
##  4 gdp_per_capita              2880
##  5 population                   110
##  6 sex_id                         0
##  7 sex_name                       0
##  8 age_name                       0
##  9 val                            0
## 10 upper                          0
## 11 lower                          0
## 12 mortality_per_100k           110
## 13 log_mortality_per_100k       110
## 14 year_2004                      0</code></pre>
</div>
<div id="exploratory-data-analysis" class="section level3">
<h3>Exploratory data analysis</h3>
<p>We will check the distribution of the following predictors:
<code>sex_name</code>, <code>age_name</code>, and
<code>gdp_per_capita</code></p>
<div id="sex" class="section level4">
<h4>Sex</h4>
<pre class="r"><code>sex_count = maindata %&gt;% 
  select(country_name, population, sex_name, year) %&gt;% 
  group_by(year, sex_name) %&gt;% 
  distinct(population) %&gt;% 
  mutate(count = population/100000)</code></pre>
<p>In <strong>maindata</strong>, the global sex distribution across
years was approximately balanced between males and females.</p>
<pre class="r"><code>plot_sex = ggplot(aes(x=as.factor(year),y=count,fill=sex_name, alpha = 0.5),data=sex_count)+
  geom_bar(stat=&quot;identity&quot;) +
  ggtitle(&quot;Gender distribution across 30 years&quot;) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(
    x = &quot;Year&quot;,
    y = &quot;Count/100k population&quot;
  )

plot_sex</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-4-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div id="age" class="section level4">
<h4>Age</h4>
<pre class="r"><code>age_count = maindata %&gt;% 
  select(country_name, population, age_name, year) %&gt;% 
  group_by(year,age_name) %&gt;%  
  distinct(population) %&gt;% 
  mutate(count = population/100000)</code></pre>
<p>In <strong>maindata</strong>, the global age distribution across
years was approximately balanced across the years between the five age
groups.</p>
<pre class="r"><code>plot_age = ggplot(aes(x=as.factor(year),y=count,fill=age_name, alpha = 0.5),data=age_count)+
  geom_bar(stat=&quot;identity&quot;) +
  ggtitle(&quot;Age distribution across 30 years&quot;) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(
    x = &quot;Year&quot;,
    y = &quot;Count/100k population&quot;
  )

plot_age</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-6-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div id="gdp-per-capita" class="section level4">
<h4>GDP per capita</h4>
<pre class="r"><code>gdp_count = maindata %&gt;% 
  select(country_name, population, gdp_per_capita, year) %&gt;% 
  group_by(year,gdp_per_capita) </code></pre>
<p>In <strong>maindata</strong>, global GDP per capita distribution was
right-skewed. Most of the countries had their GDP per capita less than
10,000.</p>
<pre class="r"><code>plot_gdp =  ggplot(data=maindata, aes(x=gdp_per_capita)) +
  geom_histogram(color = &quot;darkblue&quot;, fill = &quot;lightblue&quot;)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(
    title = &quot;GDP per capita distribution in 30 years&quot;,
    x = &quot;GDP per capita (k)&quot;,
    y = &quot;&quot;) + 
  scale_x_continuous(
    breaks = c(0,10000,20000, 30000, 40000, 50000), 
    labels = c(&quot;0&quot;, &quot;10k&quot;, &quot;20k&quot;, &quot;30k&quot;, &quot;40k&quot;, &quot;50k&quot;))

plot_gdp</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-8-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div
id="plots-of-the-distribution-to-main-outcome-of-interest-hiv-mortality-per-100k-population"
class="section level4">
<h4>Plots of the distribution to main outcome of interest (HIV mortality
per 100k population)</h4>
<p>First, we plot the distribution of <code>mortality_per_100k</code>.
We can see that we need to transform it to satisfy the normality
assumption. So we used a log transformation to get a more normal
distribution, and have a new variable
<code>mortality_per_100k</code>.</p>
<pre class="r"><code>regression %&gt;%
 ggplot(aes(x = mortality_per_100k)) +
 geom_histogram(color = &quot;darkblue&quot;, fill = &quot;lightblue&quot;) +
 ggtitle(&quot;Histogram of HIV deaths per 100k&quot;) +
 geom_vline( aes(xintercept = mean(mortality_per_100k)),
            linetype = &quot;dashed&quot;) +
 ylab(&quot;&quot;) +
 xlab(&quot;Estimated HIV deaths per 100k&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-9-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>regression %&gt;%
 ggplot(aes(x = log_mortality_per_100k)) +
 geom_histogram(color = &quot;darkblue&quot;, fill = &quot;lightblue&quot;) +
 ggtitle(&quot;Histogram of log(HIV deaths per 100k)&quot;) +
 geom_vline(aes(xintercept = mean(log_mortality_per_100k)),
            linetype = &quot;dashed&quot;) +
 ylab(&quot;&quot;) +
 xlab(&quot;Estimated log(HIV deaths per 100k)&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-9-2.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="linear-regression-models" class="section level3">
<h3>Linear regression models</h3>
<div id="hypothesis-1" class="section level4">
<h4>Hypothesis 1</h4>
<p>There is statistically significant relationship between the HIV
deaths per 100k and age groups, sex, year, and the country’s gdp per
capita respectively.</p>
</div>
<div id="model-1" class="section level4">
<h4>Model 1</h4>
<p><span class="math display">\[ log(mortality/100000) = \beta_0 +
\beta_1 age + \beta_2 sex + \beta_3 year + \beta_4 gdp \]</span></p>
<pre class="r"><code>regression_logit = regression %&gt;%
  mutate(log_mortality_per_100k = if_else(log_mortality_per_100k == -Inf, 0.01, log_mortality_per_100k))
  
model1_logit = lm(log_mortality_per_100k ~ age_name + sex_name + year + gdp_per_capita, data = regression_logit) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(exp_est = exp(estimate))

model1_logit %&gt;% 
  kable(&quot;html&quot;) %&gt;%
  kable_styling(full_width = FALSE, position = &quot;center&quot;) %&gt;%
  column_spec(1:4, width = &quot;2cm&quot;)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
exp_est
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 2cm; ">
(Intercept)
</td>
<td style="text-align:right;width: 2cm; ">
-83.4162000
</td>
<td style="text-align:right;width: 2cm; ">
2.6965462
</td>
<td style="text-align:right;width: 2cm; ">
-30.934460
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.0000000
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name10-24 years
</td>
<td style="text-align:right;width: 2cm; ">
-0.1839863
</td>
<td style="text-align:right;width: 2cm; ">
0.0356751
</td>
<td style="text-align:right;width: 2cm; ">
-5.157268
</td>
<td style="text-align:right;">
3e-07
</td>
<td style="text-align:right;">
0.8319472
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name25-49 years
</td>
<td style="text-align:right;width: 2cm; ">
2.2260567
</td>
<td style="text-align:right;width: 2cm; ">
0.0356751
</td>
<td style="text-align:right;width: 2cm; ">
62.397964
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
9.2632663
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name50-74 years
</td>
<td style="text-align:right;width: 2cm; ">
0.9935827
</td>
<td style="text-align:right;width: 2cm; ">
0.0356751
</td>
<td style="text-align:right;width: 2cm; ">
27.850834
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
2.7008936
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name75+ years
</td>
<td style="text-align:right;width: 2cm; ">
-2.7893764
</td>
<td style="text-align:right;width: 2cm; ">
0.0356751
</td>
<td style="text-align:right;width: 2cm; ">
-78.188220
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.0614595
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
sex_nameMale
</td>
<td style="text-align:right;width: 2cm; ">
0.4534213
</td>
<td style="text-align:right;width: 2cm; ">
0.0225629
</td>
<td style="text-align:right;width: 2cm; ">
20.095837
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
1.5736870
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
year
</td>
<td style="text-align:right;width: 2cm; ">
0.0405708
</td>
<td style="text-align:right;width: 2cm; ">
0.0013456
</td>
<td style="text-align:right;width: 2cm; ">
30.149937
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
1.0414050
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
gdp_per_capita
</td>
<td style="text-align:right;width: 2cm; ">
-0.0000394
</td>
<td style="text-align:right;width: 2cm; ">
0.0000006
</td>
<td style="text-align:right;width: 2cm; ">
-63.880393
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.9999606
</td>
</tr>
</tbody>
</table>
<p>Interpretation: The 10-24 years old has 0.83 times the HIV mortality
per 100k population compared to the 0-9 years old holding sex, year and
gdp in constant. The 25-49 years old has 9.26 times the HIV mortality
per 100k population compared to the 0-9 age years old holding sex, year
and gdp in constant. The 50-74 years old has 2.70 times the HIV
mortality per 100k population compared to the 0-9 age years old holding
sex, year and gdp in constant. The 75+ years old has 0.06 times the HIV
mortality per 100k population compared to the 0-9 age years old holding
sex, year and gdp in constant. The HIV mortality per 100k population
will increase by 4% with 1 year increase between 1990-2019 holding age,
sex, and gdp in constant. The the HIV mortality per 100k population will
decrease by 0.004% with 1 unit increase of gdp holding age, sex, and
year in constant.</p>
<p>The associations between the HIV deaths per 100k and age groups, sex,
year, and the country’s gdp per capita respectively are all
statistically significant at the level of 5%.</p>
</div>
<div id="hypothesis-2" class="section level4">
<h4>Hypothesis 2</h4>
<p>There is a significant change of the HIV deaths per 100k before and
after the year 2004 controlling for age groups, sex, and gdp per
capita.</p>
</div>
<div id="model-2" class="section level4">
<h4>Model 2</h4>
<p><span class="math display">\[ log(mortality/100000) = \beta_0 +
\beta_1 age + \beta_2 sex + \beta_3 year_{2004} +
\beta_4gdp  \]</span></p>
<pre class="r"><code>model2_logit = lm(log_mortality_per_100k ~ age_name + sex_name + year_2004 + gdp_per_capita, data = regression_logit) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(exp_est = exp(estimate))

model2_logit %&gt;% 
  kable(&quot;html&quot;) %&gt;%
  kable_styling(full_width = FALSE, position = &quot;center&quot;) %&gt;%
  column_spec(1:4, width = &quot;2cm&quot;)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
exp_est
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 2cm; ">
(Intercept)
</td>
<td style="text-align:right;width: 2cm; ">
-1.8001083
</td>
<td style="text-align:right;width: 2cm; ">
0.0311420
</td>
<td style="text-align:right;width: 2cm; ">
-57.803261
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.1652810
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name10-24 years
</td>
<td style="text-align:right;width: 2cm; ">
-0.1839863
</td>
<td style="text-align:right;width: 2cm; ">
0.0357550
</td>
<td style="text-align:right;width: 2cm; ">
-5.145753
</td>
<td style="text-align:right;">
3e-07
</td>
<td style="text-align:right;">
0.8319472
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name25-49 years
</td>
<td style="text-align:right;width: 2cm; ">
2.2260567
</td>
<td style="text-align:right;width: 2cm; ">
0.0357550
</td>
<td style="text-align:right;width: 2cm; ">
62.258651
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
9.2632663
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name50-74 years
</td>
<td style="text-align:right;width: 2cm; ">
0.9935827
</td>
<td style="text-align:right;width: 2cm; ">
0.0357550
</td>
<td style="text-align:right;width: 2cm; ">
27.788653
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
2.7008936
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
age_name75+ years
</td>
<td style="text-align:right;width: 2cm; ">
-2.7893764
</td>
<td style="text-align:right;width: 2cm; ">
0.0357550
</td>
<td style="text-align:right;width: 2cm; ">
-78.013652
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.0614595
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
sex_nameMale
</td>
<td style="text-align:right;width: 2cm; ">
0.4534213
</td>
<td style="text-align:right;width: 2cm; ">
0.0226134
</td>
<td style="text-align:right;width: 2cm; ">
20.050970
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
1.5736870
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
year_20041
</td>
<td style="text-align:right;width: 2cm; ">
-0.5889625
</td>
<td style="text-align:right;width: 2cm; ">
0.0230970
</td>
<td style="text-align:right;width: 2cm; ">
-25.499530
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.5549027
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
gdp_per_capita
</td>
<td style="text-align:right;width: 2cm; ">
-0.0000388
</td>
<td style="text-align:right;width: 2cm; ">
0.0000006
</td>
<td style="text-align:right;width: 2cm; ">
-62.787825
</td>
<td style="text-align:right;">
0e+00
</td>
<td style="text-align:right;">
0.9999612
</td>
</tr>
</tbody>
</table>
<p>Interpretation: The HIV deaths per 100k is 44.51% lower before 2004
than after 2004 after controlling for age, sex, and gdp per capita at
the level of 5% significance.</p>
</div>
<div id="hypothesis-3" class="section level4">
<h4>Hypothesis 3</h4>
<p>There is an interaction between age and sex.</p>
</div>
<div id="model-3" class="section level4">
<h4>Model 3</h4>
<p><span class="math display">\[ log(mortality/100000) = \beta_0 +
\beta_1 age + \beta_2 sex + \beta_3 year + \beta_4 gdp + \beta_5 age*sex
\]</span></p>
<pre class="r"><code>model1_compare = lm(log_mortality_per_100k ~ age_name + sex_name + year + gdp_per_capita, data = regression_logit)

model3_logit = lm(log_mortality_per_100k ~ age_name + sex_name + year + gdp_per_capita + age_name*sex_name, data = regression_logit) 

Anova(model1_compare, model3_logit)</code></pre>
<pre><code>## Anova Table (Type II tests)
## 
## Response: log_mortality_per_100k
##                Sum Sq    Df F value    Pr(&gt;F)    
## age_name       157021     4 5427.12 &lt; 2.2e-16 ***
## sex_name         2936     1  405.88 &lt; 2.2e-16 ***
## year             6608     1  913.61 &lt; 2.2e-16 ***
## gdp_per_capita  29666     1 4101.34 &lt; 2.2e-16 ***
## Residuals      413073 57108                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretation: There is an interaction between age groups and sex at
the 5% significance level, which means that gender can have different
impacts on the HIV deaths per 100k regarding to different age
groups.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
