---
title: "Regression Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
--- 

```{r,include=FALSE,message=FALSE,echo=FALSE}
library(tidyverse)
library(ggplot2)
library(broom)
library(plotly)
library(highcharter)
library(rworldmap)
library(gganimate)
library(transformr)
library(corrplot)
library(leaps)
library(kableExtra)
library(modelr)
library(mgcv)
library(magick)
library(readr)
library(gifski)

knitr::opts_chunk$set(
echo = FALSE,
fig.width = 7,
fig.height = 5,
fig.asp = 0.6,
out.width = "60%")
theme_set(theme_bw() +
         theme(legend.position = "bottom",
               legend.title = element_blank(),
               plot.title = element_text(hjust = 0.5, size = 15),
               plot.subtitle = element_text(hjust = 0.5, size = 12)))

maindata = read_csv("data/maindata.csv") 
```

#### Create "motality_per_100k" and "log_motality_per_100k" variables

```{r, message = FALSE,warning = FALSE}
regression = maindata %>%
 mutate(motality_per_100k = val / (population/100000),
        log_motality_per_100k = log(motality_per_100k))
regression %>%
 summarize(col_name = colnames(regression),
           n_missing = map(regression, ~sum(is.na(.)))) %>%
 unnest(n_missing)
```

### Plots of the distribution to main outcome of interest(HIV mortality per 100k population).
```{r, message = FALSE,warning = FALSE}
regression %>%
 ggplot(aes(x = motality_per_100k)) +
 geom_histogram(color = "darkblue", fill = "lightblue") +
 ggtitle("Histogram of HIV deaths per 100k") +
 geom_vline( aes(xintercept = mean(motality_per_100k)),
            linetype = "dashed") +
 ylab("") +
 xlab("Estimated HIV deaths per 100k")

regression %>%
 ggplot(aes(x = log_motality_per_100k)) +
 geom_histogram(color = "darkblue", fill = "lightblue") +
 ggtitle("Histogram of log(HIV deaths per 100k)") +
 geom_vline(aes(xintercept = mean(log_motality_per_100k)),
            linetype = "dashed") +
 ylab("") +
 xlab("Estimated log(HIV deaths per 100k)")
```

### Regression models

### model 1:

$$ log(motality/100000) = \beta_0 + \beta_1 age + \beta_2 sex + \beta_3 year + \beta_4 gdp $$
```{r}
regression_0.01 = regression %>%
 mutate(log_motality_per_100k = if_else(log_motality_per_100k == -Inf, 0.01, log_motality_per_100k),
        age_name = as.factor(age_name),
        sex_name = as.factor(sex_name))

model1 = lm(log_motality_per_100k ~ age_name + sex_name + year + gdp_per_capita, data = regression_0.01)
kable(summary(model1)$coefficients)

regression_0.01 %>%
 add_predictions(model1) %>%
 add_residuals(model1) %>%
 ggplot(aes(x = pred, y = resid)) + geom_point()
```

### model 2:

$$ log(motality/100000) = \beta_0 + \beta_1 age + \beta_2 sex + \beta_3 year_{2004} + \beta_4 gdp $$
```{r}
regression_year = regression_0.01 %>%
        mutate(year_2004 = if_else(year <= 2004, 1, 0))

model2 = lm(log_motality_per_100k ~ age_name + sex_name + year_2004 + gdp_per_capita, data = regression_year)
kable(summary(model2)$coefficients)

regression_year %>%
 add_predictions(model2) %>%
 add_residuals(model2) %>%
 ggplot(aes(x = pred, y = resid)) + geom_point()
```

### model 3:

$$ log(motality/100000) = \beta_0 + \beta_1 age + \beta_2 sex + \beta_3 year_{2004} + \beta_4 gdp + \beta_5 age*sex $$

```{r}
model3 = lm(log_motality_per_100k ~ age_name + sex_name + year_2004 + gdp_per_capita + age_name*sex_name, data = regression_year)

kable(summary(model3)$coefficients)

regression_year %>%
 add_predictions(model3) %>%
 add_residuals(model3) %>%
 ggplot(aes(x = pred, y = resid)) + geom_point()
```

### model 4:
$$ log(motality/100000) = \beta_0 + \beta_1 age + \beta_2 sex + \beta_3 year_{2004} + \beta_4 gdp + \beta_5 age*sex + \beta_6 country$$



