---
title: "Final Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
--- 

### Group members 
* Juan Cambeiro (jc5313)
* Jiaxin Wu (jw4007) 
* Liping Lu (ll3407)
* Thirsten Stockton (tjs2193)
* Kiran Kui (yk2959)

### Background and Motivation

Human immunodeficiency virus (HIV) is a retrovirus that attacks and weakens the immune system, making it difficult for the body to fight off other infections and diseases. Acquired Immunodeficiency Syndrome (AIDS) is the most advanced stage of HIV infection, when the immune system is severely weakened and the body is unable to fight off life-threatening infections and diseases.

The first cases of HIV/AIDS were reported in the United States in the early 1980s, and the disease quickly spread around the world. In the early years of the epidemic, HIV/AIDS was associated with specific risk groups, such as gay men and intravenous drug users. However, as the disease spread, it became clear that anyone could contract HIV, regardless of their sexual orientation or lifestyle.

Over the past several decades, significant progress has been made in the fight against HIV/AIDS. Antiretroviral therapy (ART) has greatly improved the health and longevity of people living with HIV, and the use of condoms and other preventive measures has helped to reduce the spread of the virus. 

However, HIV/AIDS remains a major global health problem, with millions of new infections and deaths each year. It continues to wreak devastating impacts across the world, and in particular in low-and-middle income countries that have limited resources to address it. It is therefore important and timely to study trends in HIV/AIDS in countries across the world as well as stratified by sociodemographic variables to determine communities and subgroups who are most impacted by the disease. Furthermore, it is important to determine the predictors of HIV/AIDS deaths to develop targeted policies and legislation that can prevent or slow the spread of HIV/AIDS.

### Related work

We had originally planned our final project to be about monkeypox case trends in NYC, given that timeliness of the issue. But as we were looking over our datasets for merging and exploratory analysis, we realized that we do not actually have that much to work with when it comes to the NYC monkeypox cases dataset since the monkeypox cases are not stratified by any variables like age or sex. 

We got the idea to do the same analysis we had intended for monkeypox but for HIV/AIDS after reading an [article](https://news.un.org/en/story/2022/11/1131092) about how progress on HIV treatment and prevention has flatlined over the past 3 years. We thus proceeded with the HIV/AIDS project idea.

### Initial questions

We first wanted to assess how the HIV/AIDS epidemic had unfolded over time, specifically focusing on general trends, differences by sex, differences by age, and the relationship between how developed a country is (GDP) and HIV/AIDS mortality rate across time.


### Data

Our final data set contained 60000 observations with 11 variables.Some important variables include: 

  * `country_name` : Country corresponding to data.
  * `year` : Year corresponding to data.
  * `gdp_per_capita` : Measure of a countries development.
  * `population ` : Total population size.
  * `sex_id` 
  * `age_name` : Age group (e.g., "0-9", "10-24", "25-49","50-74","75+")
  * `val` : Number of HIV/AIDS deaths
 
 his data set was created by merging three separate data sets containing information on HIV deaths, GDP per capita and population by country respectively. 

### Exploratory Analysis

We wanted to determine global trends of HIV deaths over time. We plotted estimated global HIV mortality per 100k population across 200 countries from 1990 to 2019. We did this by first grouping by year, then generating a sum of HIV mortality per 100k population for all countries for each year between 1990 and 2019. We then plotted the sum of HIV mortality per 100k population against years using ggplot. We also used transition reveal to reveal HIV mortality per 100k population gradually with increasing years. Based on the figure generated, the global HIV mortality rate. The estimated global HIV mortality rate increased from 1990, reached a peak in 2004, and decreased from 2005 to 2019.
We then wanted to determine global trends of HIV deaths over time, stratified by sex. We plotted estimated global HIV mortality per 100k population across 200 countries from 1990 to 2019, stratified by sex. We did this by first grouping by year and sex, then generating a sum of HIV mortality per 100k population for all countries for each year between 1990 and 2019, stratified by both year and sex. We then plotted the sum of HIV mortality per 100k population against years, for females and males respectively, using ggplot. We also used transition reveal to reveal HIV mortality per 100k population for females and males gradually with increasing years. Based on the figure generated, the trajectories of estimated global HIV mortality for females and males from 1990 to 2019 were similar. Before 1994 and after 2015, the difference in the HIV mortality rate between females and males was virtually indistinguishable. But from 1994 to 2015, the yearly global HIV mortality rate for females was higher than that for males.

Additionally, We also wanted to determine global trends of HIV deaths over time, stratified by age groups (0-9 years, 10-24 years, 25-49 years, 50-74 years and 75+ years). We plotted estimated global HIV mortality per 100k population across 200 countries from 1990 to 2019, stratified by age groups. We did this by first grouping by year and age group, then generating a sum of HIV mortality per 100k population for all countries for each year between 1990 and 2019, stratified by both year and age group. We then plotted the sum of HIV mortality per 100k population against years, for each of the different age groups, using ggplot. We also used transition reveal to reveal HIV mortality per 100k population for the age groups gradually with increasing years. Generally, the estimated global HIV mortality rates from 1990 to 2019 were the highest among young or middle-aged adults (25-49 years), and were the lowest among the elderly (75+ years). Among young or middle-aged adults, the global HIV mortality rate changed the most from 1990 to 2019, with the peak occurring in 2004. The mortality trends were more stable for people in other age groups (0-9 years, 10-24 years, 50-74 years, and 75+ years). Among the people aged over 75 years old, the global HIV mortality rates during the 30 years were low and stable.

Next, we wanted to explore the relationship between GDP per capita and HIV deaths over time. In order to do this, we created a plot with GDP per capita on our x-axis and HIV mortality rate per 100k on our y-axis. We first grouped our data by year, country, and GDP per capita, then generated a sum of HIV mortality per 100k population for every country for each year between 1990 and 2019. Using ggplot, we then created a scatter plot, plotting each country's GDP per capita against their given HIV mortality rate. We also employed transition time in order to assess how this relationship had changed over time. In general, there seemed to be a non-linear negative association between GDP and HIV mortality rate. This may be indicative of the fact that poorer countries do not have adequate resources to avert otherwise preventable HIV/AIDS deaths.
 
We additionally wanted to examine how countries rank in terms of their numbers of HIV deaths across the years. We first created a table showing the top 10 countries with the highest total number of HIV deaths. In order to do this, we grouped our data by country and summed together their total amount of HIV deaths from 1990 to 2019. Next, we arranged this data in descending order and selected the first 10, yielding a table showing the top 10 countries. This table revealed that South Africa had the highest total number of HIV deaths across the years, with a total of 4,864,295, which was over two million more than the second ranked country, Kenya. In addition to this, we also created a visualization showing how the total number of HIV deaths had changed from 1990-2019 for the top 10 countries. This visualization was created in ggplot and used transition states and animation to show how rankings and total HIV death counts changed from year to year. This visualization allowed us to gain a better insight into how the HIV/AIDS epidemic has unfolded in each respective country over the years. For example, in the early 1990s, South Africa had relatively few deaths in comparison to the other countries in our list, but they quickly rose to the top in the 2000s.
 
We also wanted to examine how countries rank in terms of total number of HIV deaths, controlling for the population size (per 100k). Similar to the prior analysis, we first created a table showing the top 10 countries with the highest HIV mortality per 100k. This was done by grouping our data by both year and county and summing the total number of HIV deaths per 100k. Next, we arranged this data in descending order and selected the first 10, yielding a table showing the top 10 countries. Differing from the unadjusted HIV death rankings, Lesotho’s had the highest rate of HIV mortality per 100k, followed by Eswatini and Zimbabwe. In addition to this table, we also created a table featuring the countries with the top 10 countries with the lowest HIV mortality rate per 100k. This table was created in a similar fashion to the previous table, but instead, we ranked the data in ascending order. Data showed that Albania had the lowest total HIV rate per 100k, followed by Slovakia and Bosnia and Herzegovina. Corresponding visualizations were made for both the top 10 highest and top 10 lowest countries to show how the rankings and HIV mortality rate had changed by year. This was done using ggplot with transition states and animation. An interesting takeaway from these visualizations is that some countries in the top 10 lowest list had an HIV mortality rate of zero for a better part of the 1990s. Eventually all countries were touched by this epidemic in some form though.


### Regression Analysis

Our regression models are built around answering our initial questions: does HIV/AIDS mortality differ between different sexes, age groups, and the level of development of the countries? If so, how meaningful are these differences?
 
First, we hypothesized that HIV/AIDS mortality rate for each country is associated with gender, age, year, and GDP per capita (a proxy of the level of development). This hypothesis is validated by the output of the model. All the covariates (gender, age groups, year, and GDP) are all statistically significant at the level of 5%. Notably, the age group that has the highest HIV/AIDS mortality is the 25-49 years old after controlling for other covariates. It is 9.26 times the mortality rate of the 0-9 years old.
 
Second, we wanted to further explore the change of HIV/AIDS mortality over time. From the graphs for exploratory analysis, we saw the mortality rate of HIV/AIDS dropped after the year 2004. So, we wanted to know if the mortality rate is significantly different before and after 2004. The second model with the “year 2004” indicator variable shows that the HIV deaths per 100k is 44.51% lower before 2004 than after 2004 at the level of 5% significance, after controlling for age, sex, and GDP.
 
Third, we would like to explore whether HIV/AIDS mortality could differ by sex for the same age groups. By adding interaction terms between sex and age groups, we were able to confirm that sex can have differential impacts on  mortality by age group.

### Discussion

By analyzing the dataset which included the estimated HIV mortality per 100k population among 200 countries from 1990 to 2019, we observed that the global trend of HIV mortality showed a bell shape, with a peak in 2004. In the adjusted logistic regression models, HIV mortality was associated with age groups (0-9 years, 10-24 years, 25-49 years, 50-74 years, and 75+ years), sex (females and males), GDP per capita, and the interaction between age and sex. Compared to males, females had a higher odds of HIV mortality. Adults aged between 25 to 49 years old had the highest HIV mortality among all populations, while the elderly aged over 75 years old had the lowest HIV mortality. HIV mortality was negatively associated with country GDP per capita.

Before 2004,  HIV mortality increased steeply by year. Since 2000, remarkable progress has been made in the diagnosis and treatment of persons living with HIV/AIDS, which has contributed to the decline of global HIV mortality. However, many people with HIV still do not have access to prevention, care, and treatment, especially in the countries under poverty. Women and young or middle-aged adults are two populations with high risk of HIV mortality. This is probably because in many countries women have a limited role in sexual decision-making and protection. Moreover, young or middle-aged adults are more likely to have particular HIV risk behaviors, including sexual activity and drug abuse.

A few limitations should not be neglected. Some potential risk factors (e.g., race, education levels, sexual activities, drug abuse) were not included in this study. In addition, many countries lack the information on GDP per capita as well as on population size, which reduces the statistical power.

The large dataset provides a comprehensive picture of global HIV mortality over a 30-year period. Our findings call for more attention to the populations and countries at high risk of HIV mortality. 


### References

Danforth K, Granich R, Wiedeman D, Baxi S, Padian N. Global mortality and morbidity of HIV/AIDS. Major infectious         diseases Washington, DC: The International Bank for Reconstruction and Development/The World Bank. 2017.

GDP per capita (current US$). World Bank. (2022, September 16). Retrieved December 9, 2022, from                          https://data.worldbank.org/indicator/NY.GDP.PCAP.CD 

Global Burden of Disease Collaborative Network.
    Global Burden of Disease Study 2019 (GBD 2019) Results.
    Seattle, United States: Institute for Health Metrics and Evaluation (IHME), 2020.
    Available from https://vizhub.healthdata.org/gbd-results/
    
Global HIV &amp; AIDS statistics - fact sheet. UNAIDS. (n.d.). Retrieved December 9, 2022, from                           https://www.unaids.org/en/resources/fact-sheet 

Greig A, Peacock D, Jewkes R, Msimang S. Gender and AIDS: time to act. Aids. 2008;22 Suppl 2(Suppl 2):S35-43.

HIV historical timeline. HIV Historical Timeline. (n.d.). Retrieved December 9, 2022, from https://hivhistory.org/ 

Population, total. World Bank. (2022, September 16). Retrieved December 9, 2022, from                                     https://data.worldbank.org/indicator/SP.POP.TOTL 